import type { PropDef } from "../types/editor.js";

export const ENERGY_TYPES = [
  "Grass",
  "Fire",
  "Water",
  "Lightning",
  "Psychic",
  "Fighting",
  "Darkness",
  "Metal",
  "Fairy",
  "Dragon",
  "Colorless",
] as const;

export const PROP_DEFS: Record<string, PropDef[]> = {
  box: [
    { key: "anchorX", label: "Anchor X", type: "number", min: -200, max: 900, step: 1, isPosition: true },
    { key: "anchorY", label: "Anchor Y", type: "number", min: -200, max: 1100, step: 1, isPosition: true },
    { key: "direction", label: "Direction", type: "select", options: ["row", "row-reverse", "column"] },
    { key: "width", label: "Width", type: "number", min: 0, max: 900, step: 1 },
    { key: "gap", label: "Gap", type: "number", min: 0, max: 50, step: 1 },
    { key: "vAnchor", label: "V-Anchor", type: "select", options: ["top", "bottom"] },
    { key: "marginTop", label: "Margin Top", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginRight", label: "Margin Right", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginBottom", label: "Margin Bottom", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginLeft", label: "Margin Left", type: "number", min: -50, max: 50, step: 1 },
    { key: "paddingTop", label: "Pad Top", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingRight", label: "Pad Right", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingBottom", label: "Pad Bottom", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingLeft", label: "Pad Left", type: "number", min: 0, max: 50, step: 1 },
    { key: "fill", label: "Fill", type: "color" },
    { key: "fillOpacity", label: "Fill Opacity", type: "range", min: 0, max: 1, step: 0.05 },
    { key: "rx", label: "Corner Radius", type: "number", min: 0, max: 30, step: 1 },
  ],
  image: [
    { key: "anchorX", label: "Anchor X", type: "number", min: -200, max: 900, step: 1, isPosition: true },
    { key: "anchorY", label: "Anchor Y", type: "number", min: -200, max: 1100, step: 1, isPosition: true },
    { key: "src", label: "Source", type: "select", options: ["energy", "logo"] },
    { key: "energyType", label: "Type", type: "select", options: [...ENERGY_TYPES] },
    { key: "radius", label: "Radius", type: "number", min: 5, max: 60, step: 1 },
    { key: "suffix", label: "Logo", type: "select", options: ["V", "ex", "VSTAR", "VSTAR-big"] },
    { key: "height", label: "Height", type: "range", min: 10, max: 600, step: 1 },
    { key: "opacity", label: "Opacity", type: "range", min: 0, max: 1, step: 0.05 },
    { key: "clipToCard", label: "Clip", type: "select", options: ["0", "1"] },
    { key: "filter", label: "Filter", type: "select", options: ["none", "shadow", "title-shadow"] },
  ],
};

export const SUB_PROP_DEFS: Record<string, PropDef[]> = {
  text: [
    { key: "text", label: "Text", type: "text" },
    { key: "fontSize", label: "Font Size", type: "number", min: 8, max: 120, step: 1 },
    { key: "fontFamily", label: "Font", type: "select", options: ["title", "body"] },
    { key: "fontWeight", label: "Weight", type: "select", options: ["normal", "bold"] },
    { key: "fill", label: "Fill", type: "color" },
    { key: "opacity", label: "Opacity", type: "range", min: 0, max: 1, step: 0.05 },
    { key: "stroke", label: "Stroke", type: "color" },
    { key: "strokeWidth", label: "Stroke W", type: "number", min: 0, max: 10, step: 0.5 },
    { key: "filter", label: "Filter", type: "select", options: ["none", "shadow", "title-shadow", "dmg-shadow"] },
    { key: "textAnchor", label: "Anchor", type: "select", options: ["start", "middle", "end"] },
    { key: "wrap", label: "Wrap", type: "select", options: ["0", "1"] },
    { key: "grow", label: "Grow", type: "number", min: 0, max: 10, step: 1 },
    { key: "hAlign", label: "H-Align", type: "select", options: ["start", "center", "end"] },
    { key: "marginTop", label: "Margin Top", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginRight", label: "Margin Right", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginBottom", label: "Margin Bottom", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginLeft", label: "Margin Left", type: "number", min: -50, max: 50, step: 1 },
    { key: "paddingTop", label: "Pad Top", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingRight", label: "Pad Right", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingBottom", label: "Pad Bottom", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingLeft", label: "Pad Left", type: "number", min: 0, max: 50, step: 1 },
    { key: "vAlign", label: "V-Align", type: "select", options: ["top", "middle", "bottom"] },
  ],
  image: [
    { key: "src", label: "Source", type: "select", options: ["energy", "logo"] },
    { key: "energyType", label: "Type", type: "select", options: [...ENERGY_TYPES] },
    { key: "radius", label: "Radius", type: "number", min: 5, max: 60, step: 1 },
    { key: "suffix", label: "Logo", type: "select", options: ["V", "ex", "VSTAR", "VSTAR-big"] },
    { key: "height", label: "Height", type: "number", min: 10, max: 600, step: 1 },
    { key: "opacity", label: "Opacity", type: "range", min: 0, max: 1, step: 0.05 },
    { key: "clipToCard", label: "Clip", type: "select", options: ["0", "1"] },
    { key: "filter", label: "Filter", type: "select", options: ["none", "shadow", "title-shadow"] },
    { key: "grow", label: "Grow", type: "number", min: 0, max: 10, step: 1 },
    { key: "hAlign", label: "H-Align", type: "select", options: ["start", "center", "end"] },
    { key: "marginTop", label: "Margin Top", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginRight", label: "Margin Right", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginBottom", label: "Margin Bottom", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginLeft", label: "Margin Left", type: "number", min: -50, max: 50, step: 1 },
    { key: "paddingTop", label: "Pad Top", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingRight", label: "Pad Right", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingBottom", label: "Pad Bottom", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingLeft", label: "Pad Left", type: "number", min: 0, max: 50, step: 1 },
    { key: "vAlign", label: "V-Align", type: "select", options: ["top", "middle", "bottom"] },
  ],
  box: [
    { key: "direction", label: "Direction", type: "select", options: ["row", "row-reverse", "column"] },
    { key: "width", label: "Width", type: "number", min: 0, max: 900, step: 1 },
    { key: "gap", label: "Gap", type: "number", min: 0, max: 50, step: 1 },
    { key: "fill", label: "Fill", type: "color" },
    { key: "fillOpacity", label: "Fill Opacity", type: "range", min: 0, max: 1, step: 0.05 },
    { key: "rx", label: "Corner Radius", type: "number", min: 0, max: 30, step: 1 },
    { key: "grow", label: "Grow", type: "number", min: 0, max: 10, step: 1 },
    { key: "hAlign", label: "H-Align", type: "select", options: ["start", "center", "end"] },
    { key: "marginTop", label: "Margin Top", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginRight", label: "Margin Right", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginBottom", label: "Margin Bottom", type: "number", min: -50, max: 50, step: 1 },
    { key: "marginLeft", label: "Margin Left", type: "number", min: -50, max: 50, step: 1 },
    { key: "paddingTop", label: "Pad Top", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingRight", label: "Pad Right", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingBottom", label: "Pad Bottom", type: "number", min: 0, max: 50, step: 1 },
    { key: "paddingLeft", label: "Pad Left", type: "number", min: 0, max: 50, step: 1 },
    { key: "vAlign", label: "V-Align", type: "select", options: ["top", "middle", "bottom"] },
  ],
};

export const BOX_MODEL_KEYS: Record<string, boolean> = {
  marginTop: true, marginRight: true, marginBottom: true, marginLeft: true,
  paddingTop: true, paddingRight: true, paddingBottom: true, paddingLeft: true,
};

export const FILL_KEYS: Record<string, boolean> = {
  fill: true, fillOpacity: true, opacity: true,
};
